### PR TITLE
Add Nix

### PR DESCRIPTION
**Pull request by emanueljg**
This PR adds support for Nix and NixOS. I'm already running this ref on my personal server and everything seems to work fine, but please make sure it works for you too on your end.

Furthermore, it could be a good idea to add Nix-specific tests in CI to make sure master never breaks. I recommend [garnix.io](https://garnix.io/) in this case, which would do 2 things:
1) check the validity of the flake, checking its outputs (for a showcase on how this works, check my fork of this repo)
2) being able to spin up a simple NixOS VM running automated tests for the nixos module on each PR (this is a recent addition to Garnix). This would not only test NixOS usage but also general testing for the service.

### CODE REVIEW

**Comment by marcopeocchi** [comment]
Great! I'm testing it ASAP!

**Comment by emanueljg** [comment]
Update: I pushed some trivial polishing changes ([8208b59](https://github.com/marcopeocchi/yt-dlp-web-ui/pull/177/commits/8208b590ee062be4240e3484b6f0de3b7079aaae)..[bb409a8](https://github.com/marcopeocchi/yt-dlp-web-ui/pull/177/commits/bb409a876e61cfebd524f6c98d6ef107ec3f6b11)). Additionally, I edited my PR comment with some advice regarding CI.

**Comment by marcopeocchi** [comment]
First of all thanks for this PR!

I'm goint to merge it but i need some time to understand the CI pipeline. 😄

**Comment by marcopeocchi** [comment]
I've just checked... mega work! Thanks again!

**Comment by akho** [comment]
I think something got misaligned, and `go.mod` was updated between the point this was written and now. the `vendorHash` in `server.nix` is now incorrect, and the package does not build. Should be 

```
sha256-AqAS3+fjC1IyUgG9SDxvAiwIu9iE8a65skRKBq6tsv8=
```

**Pull request merged**
