### PR TITLE
unix socket support (useful behind nginx proxy)

### PR DESCRIPTION
**Pull request by cyberb**
I am maintainer of https://github.com/syncloud/platform where I help non tech people with self-hosting popular apps.

I would like to add your app as it is easy to use, but I would like to add unix socket support as I am not using ports (tcp) for running multiple apps on a single PC for maintenance simplicity purposes.

### CODE REVIEW

**Comment by cyberb** [comment]
I see you are using logger.Error to log errors but you are not returning and I do not thing that library panics either.
That makes app to continue the execution which makes it fail later with potentially another error, I think it is practical to fail fast usually by returning the err.

**Comment by marcopeocchi** [comment]
Hi @cyberb,

You're right, my bad slog.Error does not end the current goroutine execution. I will take it in consideration, anyway points where the app needs to immediate stop are few.

Regarding your PR: thank for you wanting to feature my project into syncloud, supporting UNIX sockets it's a nice addition.

**Comment by cyberb** [comment]
Thanks, do you plan a release at some point?

**Comment by marcopeocchi** [comment]
I will issue a new release Once I will test the "file base logging feature" I was working on (might be even today evening).

**Pull request merged**
